name: CICD Docker + Telegram Notification

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/cicd-workflow2.yml"
      - ".github/scripts/custom.sh"
      - "Dockerfile"
      - "docker-compose.yml"
      - "server.js"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env << 'EOF'
          ${{ secrets.PROD_ENV2 }}
          EOF

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/class_ci-cd:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/class_ci-cd:latest

  deploy:
    needs: build
    runs-on: [self-hosted, linux]
    environment: PROD
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run custom script
        run: |
          chmod +x .github/scripts/custom.sh
          .github/scripts/custom.sh
        shell: bash

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/class_ci-cd:latest

      - name: Delete old container
        run: docker rm -f class_ci-cd || true

      - name: Run docker container
        run: docker run -d -p ${{ secrets.PORT_RUN_CONTAINER }} --name class_ci-cd ${{ secrets.DOCKER_HUB_USERNAME }}/class_ci-cd:latest

  notification:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Workflow: ${{ github.workflow }}
            Status: ${{ needs.deploy.result }}
            Actor: ${{ github.actor }}
            Commit: ${{ github.event.head_commit.message }}
            Repo: ${{ github.repository }}
            URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
